// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq3zApQokBTWpq-SVQB5DMUra6gQrUc2E',
    appId: '1:792861237507:web:34e6ed06e948e92bbc8936',
    messagingSenderId: '792861237507',
    projectId: 'hgtt-e0a99',
    authDomain: 'hgtt-e0a99.firebaseapp.com',
    storageBucket: 'hgtt-e0a99.appspot.com',
    measurementId: 'G-JGDYB74863',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKCSOYALuQv2ll2sNejm2Z5hKvN3aEM2Q',
    appId: '1:792861237507:android:9587d2f117ec7b7ebc8936',
    messagingSenderId: '792861237507',
    projectId: 'hgtt-e0a99',
    storageBucket: 'hgtt-e0a99.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxYgYaElt-4BFwqR1FZ6H3mzY72b41NoA',
    appId: '1:792861237507:ios:b7d36ad17c5d0f04bc8936',
    messagingSenderId: '792861237507',
    projectId: 'hgtt-e0a99',
    storageBucket: 'hgtt-e0a99.appspot.com',
    iosClientId: '792861237507-lv2siv62so0paqu3k01gudti6vovdne3.apps.googleusercontent.com',
    iosBundleId: 'com.example.hgt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxYgYaElt-4BFwqR1FZ6H3mzY72b41NoA',
    appId: '1:792861237507:ios:fac272289b852a5fbc8936',
    messagingSenderId: '792861237507',
    projectId: 'hgtt-e0a99',
    storageBucket: 'hgtt-e0a99.appspot.com',
    iosClientId: '792861237507-53uejsijutua0kpasqf9cho4bjqvh26e.apps.googleusercontent.com',
    iosBundleId: 'com.example.hgt.RunnerTests',
  );
}
